services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_AUTH_CLIENT_ID=8qNA2sSV88fusOocZcMj6GirTLWYygdAXnmtLUfe
      - VITE_BACKEND_URL=http://localhost:8080

  project-management-service:
    build:
      context: ./project-management-service
      dockerfile: Dockerfile
    container_name: project-management-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://project-management-db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - project-management-db

  project-management-db:
    image: postgres:16
    container_name: project-management-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - project_management_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - user-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: change-me
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  observability-service:
    build:
      context: ./observability-service
      dockerfile: Dockerfile
    container_name: observability-service
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - PROMETHEUS_URL=http://host.docker.internal:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project-management-service
      - user-service
      - observability-service

volumes:
  project_management_data:
  user_db_data:
