server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.kleff: DEBUG

# CORS configuration
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000

prometheus:
  # For local testing with port-forward
  url: http://localhost:9090

  # For running in Kubernetes cluster (uncomment when deploying)
  # url: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090