apiVersion: kleff.kleff.io/v1
kind: WebApp
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: webapp-sample
spec:
  displayName: "My Production App"
  repoURL: "https://github.com/my-org/my-repo.git"
  branch: "main"
  image: "nginx:1.25.3"
  port: 8080