---
name: Build and Push to ACR
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
    strategy:
      matrix:
        service:
          - name: frontend
            context: ./frontend
            tag: frontend
          - name: project-management
            context: ./project-management-service
            tag: project-management-service
          - name: deployment
            context: ./deployment-service
            tag: deployment-service
          - name: observability
            context: ./observability-service
            tag: observability-service
          - name: user
            context: ./user-service
            tag: user-service
          - name: server-api
            context: ./server-apis
            tag: deployment-backend
          - name: billing-service
            context: ./billing-service
            tag: billing-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.service.tag }}:latest
            ${{ env.REGISTRY }}/${{ matrix.service.tag }}:${{ github.sha }}
          build-args: |
            VITE_AUTH_CLIENT_ID=${{ vars.VITE_AUTH_CLIENT_ID }}
            VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }}

  build-operator:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Operator
        working-directory: ./operator
        run: |
          make docker-buildx \
            IMG="${{ env.REGISTRY }}/webapp-operator:latest" \
            PLATFORMS="linux/amd64,linux/arm64"
          make build-installer \
            IMG="${{ env.REGISTRY }}/webapp-operator:latest"
